// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountType.
const (
	Asset     AccountType = "asset"
	Equity    AccountType = "equity"
	Expense   AccountType = "expense"
	Income    AccountType = "income"
	Liability AccountType = "liability"
)

// Valid indicates whether the value is a known member of the AccountType enum.
func (e AccountType) Valid() bool {
	switch e {
	case Asset:
		return true
	case Equity:
		return true
	case Expense:
		return true
	case Income:
		return true
	case Liability:
		return true
	default:
		return false
	}
}

// Defines values for EntrySource.
const (
	EntrySourceImport    EntrySource = "import"
	EntrySourceManual    EntrySource = "manual"
	EntrySourceRecurring EntrySource = "recurring"
)

// Valid indicates whether the value is a known member of the EntrySource enum.
func (e EntrySource) Valid() bool {
	switch e {
	case EntrySourceImport:
		return true
	case EntrySourceManual:
		return true
	case EntrySourceRecurring:
		return true
	default:
		return false
	}
}

// Defines values for EntryStatus.
const (
	Draft  EntryStatus = "draft"
	Posted EntryStatus = "posted"
)

// Valid indicates whether the value is a known member of the EntryStatus enum.
func (e EntryStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusDb.
const (
	Down HealthStatusDb = "down"
	Up   HealthStatusDb = "up"
)

// Valid indicates whether the value is a known member of the HealthStatusDb enum.
func (e HealthStatusDb) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for JournalLineDc.
const (
	JournalLineDcCredit JournalLineDc = "credit"
	JournalLineDcDebit  JournalLineDc = "debit"
)

// Valid indicates whether the value is a known member of the JournalLineDc enum.
func (e JournalLineDc) Valid() bool {
	switch e {
	case JournalLineDcCredit:
		return true
	case JournalLineDcDebit:
		return true
	default:
		return false
	}
}

// Defines values for LineInputDc.
const (
	LineInputDcCredit LineInputDc = "credit"
	LineInputDcDebit  LineInputDc = "debit"
)

// Valid indicates whether the value is a known member of the LineInputDc enum.
func (e LineInputDc) Valid() bool {
	switch e {
	case LineInputDcCredit:
		return true
	case LineInputDcDebit:
		return true
	default:
		return false
	}
}

// Defines values for NewEntryRequestSource.
const (
	NewEntryRequestSourceImport    NewEntryRequestSource = "import"
	NewEntryRequestSourceManual    NewEntryRequestSource = "manual"
	NewEntryRequestSourceRecurring NewEntryRequestSource = "recurring"
)

// Valid indicates whether the value is a known member of the NewEntryRequestSource enum.
func (e NewEntryRequestSource) Valid() bool {
	switch e {
	case NewEntryRequestSourceImport:
		return true
	case NewEntryRequestSourceManual:
		return true
	case NewEntryRequestSourceRecurring:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Archived  bool      `json:"archived"`
	CreatedAt time.Time `json:"created_at"`

	// Currency ISO 4217 currency code
	//
	// Example: IDR
	Currency string `json:"currency"`

	// Id client-generated id (WatermelonDB) or server uuid
	Id   string `json:"id"`
	Name string `json:"name"`

	// ParentId optional parent account (tree hook; unused in M2)
	ParentId *string `json:"parent_id,omitempty"`

	// Type Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
	Type      AccountType `json:"type"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// AccountBalance defines model for AccountBalance.
type AccountBalance struct {
	AccountId   string `json:"account_id"`
	CreditMinor int64  `json:"credit_minor"`

	// Currency Example: IDR
	Currency   string `json:"currency"`
	DebitMinor int64  `json:"debit_minor"`

	// SignedMinor normal-balance-signed amount (asset/expense = debit−credit; others = credit−debit); positive is healthy/normal
	SignedMinor int64 `json:"signed_minor"`
}

// AccountType Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
type AccountType string

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken short-lived HS256 JWT; send as `Authorization: Bearer <token>`
	AccessToken string `json:"access_token"`

	// RefreshToken single-use opaque token; rotate via /auth/refresh
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// Budget defines model for Budget.
type Budget struct {
	AccountId string    `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`

	// Currency Example: IDR
	Currency    string             `json:"currency"`
	Id          string             `json:"id"`
	PeriodMonth openapi_types.Date `json:"period_month"`
	TargetMinor int64              `json:"target_minor"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// BudgetWithSpent defines model for BudgetWithSpent.
type BudgetWithSpent struct {
	AccountId string    `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`

	// Currency Example: IDR
	Currency    string             `json:"currency"`
	Id          string             `json:"id"`
	PeriodMonth openapi_types.Date `json:"period_month"`

	// SpentMinor actual spending so far this month
	SpentMinor  int64     `json:"spent_minor"`
	TargetMinor int64     `json:"target_minor"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Entry defines model for Entry.
type Entry struct {
	CreatedAt time.Time `json:"created_at"`

	// Currency Example: IDR
	Currency string `json:"currency"`

	// FxRate cross-currency rate (M4); null for single-currency entries
	FxRate *string `json:"fx_rate,omitempty"`

	// Id client-generated id or server uuid
	Id        string             `json:"id"`
	Lines     []JournalLine      `json:"lines"`
	Memo      string             `json:"memo"`
	Source    EntrySource        `json:"source"`
	Status    EntryStatus        `json:"status"`
	TxnDate   openapi_types.Date `json:"txn_date"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// EntrySource defines model for Entry.Source.
type EntrySource string

// EntryStatus defines model for Entry.Status.
type EntryStatus string

// Error defines model for Error.
type Error struct {
	// Code stable machine code for this error class
	//
	// Example: invalid_credentials
	Code string `json:"code"`

	// Message human-readable detail
	//
	// Example: invalid credentials
	Message string `json:"message"`
}

// GoogleRequest defines model for GoogleRequest.
type GoogleRequest struct {
	// Code authorization code from expo-auth-session
	Code string `json:"code"`

	// RedirectUri the redirect URI the app used in the auth request
	RedirectUri string `json:"redirect_uri"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Db Postgres connectivity
	//
	// Example: up
	Db HealthStatusDb `json:"db"`

	// Status process liveness
	//
	// Example: ok
	Status string `json:"status"`
}

// HealthStatusDb Postgres connectivity
//
// Example: up
type HealthStatusDb string

// JournalLine defines model for JournalLine.
type JournalLine struct {
	AccountId string `json:"account_id"`

	// AmountMinor unsigned integer minor units (cents) at the currency's scale
	//
	// Example: 50000
	AmountMinor int64 `json:"amount_minor"`

	// Currency Example: IDR
	Currency string        `json:"currency"`
	Dc       JournalLineDc `json:"dc"`
	EntryId  string        `json:"entry_id"`

	// Id client-generated id
	Id string `json:"id"`
}

// JournalLineDc defines model for JournalLine.Dc.
type JournalLineDc string

// LineInput defines model for LineInput.
type LineInput struct {
	AccountId string `json:"account_id"`

	// AmountMinor unsigned minor units
	AmountMinor int64 `json:"amount_minor"`

	// Currency optional; defaults to the entry currency (M4 multi-currency support)
	//
	// Example: IDR
	Currency *string     `json:"currency,omitempty"`
	Dc       LineInputDc `json:"dc"`

	// Id optional client id; server generates a uuid when omitted
	Id *string `json:"id,omitempty"`
}

// LineInputDc defines model for LineInput.Dc.
type LineInputDc string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NewAccountRequest defines model for NewAccountRequest.
type NewAccountRequest struct {
	// Currency Example: IDR
	Currency string `json:"currency"`

	// Id optional client id; server generates a uuid when omitted (REST path)
	Id       *string `json:"id,omitempty"`
	Name     string  `json:"name"`
	ParentId *string `json:"parent_id,omitempty"`

	// Type Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
	Type AccountType `json:"type"`
}

// NewBudgetRequest defines model for NewBudgetRequest.
type NewBudgetRequest struct {
	AccountId string `json:"account_id"`

	// Id optional client id; server generates a uuid when omitted
	Id *string `json:"id,omitempty"`

	// PeriodMonth first day of the month e.g. 2026-07-01
	PeriodMonth openapi_types.Date `json:"period_month"`

	// TargetMinor budgeted amount in minor units
	TargetMinor int64 `json:"target_minor"`
}

// NewEntryRequest defines model for NewEntryRequest.
type NewEntryRequest struct {
	// Currency Example: IDR
	Currency string `json:"currency"`

	// FxRate optional cross-currency rate; when set, the balance invariant is enforced in-app (M4)
	//
	// Example: 15000.00
	FxRate *string `json:"fx_rate,omitempty"`

	// Id optional client id; server generates a uuid when omitted (REST path)
	Id     *string                `json:"id,omitempty"`
	Lines  []LineInput            `json:"lines"`
	Memo   *string                `json:"memo,omitempty"`
	Source *NewEntryRequestSource `json:"source,omitempty"`

	// TxnDate optional; defaults to today
	TxnDate *openapi_types.Date `json:"txn_date,omitempty"`
}

// NewEntryRequestSource defines model for NewEntryRequest.Source.
type NewEntryRequestSource string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// BaseCurrency optional; defaults to server BASE_CURRENCY_DEFAULT
	//
	// Example: IDR
	BaseCurrency *string             `json:"base_currency,omitempty"`
	Email        openapi_types.Email `json:"email"`
	Password     string              `json:"password"`
}

// SyncChanges map of table name -> changes, conforming to WatermelonDB protocol
type SyncChanges map[string]SyncTableChanges

// SyncPullRequest defines model for SyncPullRequest.
type SyncPullRequest struct {
	// LastPulledAt server timestamp of the last successful pull; 0 for initial sync
	LastPulledAt int64 `json:"last_pulled_at"`
}

// SyncPullResponse defines model for SyncPullResponse.
type SyncPullResponse struct {
	// Changes map of table name -> changes, conforming to WatermelonDB protocol
	Changes SyncChanges `json:"changes"`

	// Timestamp server timestamp; client sends this as last_pulled_at on the next pull
	Timestamp int64 `json:"timestamp"`
}

// SyncPushRequest defines model for SyncPushRequest.
type SyncPushRequest struct {
	// Changes map of table name -> changes, conforming to WatermelonDB protocol
	Changes SyncChanges `json:"changes"`
}

// SyncPushResponse defines model for SyncPushResponse.
type SyncPushResponse struct {
	// Errors per-record error messages for records that could not be applied (422 etc)
	Errors *[]string `json:"errors,omitempty"`
}

// SyncTableChanges defines model for SyncTableChanges.
type SyncTableChanges struct {
	Created *[]map[string]interface{} `json:"created,omitempty"`
	Deleted *[]string                 `json:"deleted,omitempty"`
	Updated *[]map[string]interface{} `json:"updated,omitempty"`
}

// UpdateBudgetRequest defines model for UpdateBudgetRequest.
type UpdateBudgetRequest struct {
	TargetMinor int64 `json:"target_minor"`
}

// User defines model for User.
type User struct {
	// BaseCurrency ISO 4217 currency code
	//
	// Example: IDR
	BaseCurrency string              `json:"base_currency"`
	CreatedAt    time.Time           `json:"created_at"`
	Email        openapi_types.Email `json:"email"`
	Id           openapi_types.UUID  `json:"id"`
}

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	Type *AccountType `form:"type,omitempty" json:"type,omitempty"`
}

// ListBudgetsParams defines parameters for ListBudgets.
type ListBudgetsParams struct {
	Month openapi_types.Date `form:"month" json:"month"`
}

// ListEntriesParams defines parameters for ListEntries.
type ListEntriesParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = NewAccountRequest

// GoogleAuthJSONRequestBody defines body for GoogleAuth for application/json ContentType.
type GoogleAuthJSONRequestBody = GoogleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// SetBudgetJSONRequestBody defines body for SetBudget for application/json ContentType.
type SetBudgetJSONRequestBody = NewBudgetRequest

// UpdateBudgetJSONRequestBody defines body for UpdateBudget for application/json ContentType.
type UpdateBudgetJSONRequestBody = UpdateBudgetRequest

// PostEntryJSONRequestBody defines body for PostEntry for application/json ContentType.
type PostEntryJSONRequestBody = NewEntryRequest

// SyncPullJSONRequestBody defines body for SyncPull for application/json ContentType.
type SyncPullJSONRequestBody = SyncPullRequest

// SyncPushJSONRequestBody defines body for SyncPush for application/json ContentType.
type SyncPushJSONRequestBody = SyncPushRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAccounts List the user's accounts (pockets and categories)
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams)
	// CreateAccount Create a pocket or category (chart-of-accounts entry)
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// GetAccountBalance Account debit/credit totals and normal-balance-signed amount
	// (GET /accounts/{id}/balance)
	GetAccountBalance(w http.ResponseWriter, r *http.Request, id string)
	// GoogleAuth Exchange a Google authorization code for a session
	// (POST /auth/google)
	GoogleAuth(w http.ResponseWriter, r *http.Request)
	// Login Exchange credentials for a session
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Revoke the presented refresh token
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetMe Current authenticated user
	// (GET /auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Refresh Rotate a refresh token into a new session
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// Register Create a credential account and start a session
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// ListBudgets List budgets for a month, with spent amounts
	// (GET /budgets)
	ListBudgets(w http.ResponseWriter, r *http.Request, params ListBudgetsParams)
	// SetBudget Create or update a monthly category budget
	// (POST /budgets)
	SetBudget(w http.ResponseWriter, r *http.Request)
	// DeleteBudget Delete a budget
	// (DELETE /budgets/{id})
	DeleteBudget(w http.ResponseWriter, r *http.Request, id string)
	// UpdateBudget Update a budget's target
	// (PUT /budgets/{id})
	UpdateBudget(w http.ResponseWriter, r *http.Request, id string)
	// ListEntries List posted entries with their lines
	// (GET /entries)
	ListEntries(w http.ResponseWriter, r *http.Request, params ListEntriesParams)
	// PostEntry Post a balanced double-entry transaction
	// (POST /entries)
	PostEntry(w http.ResponseWriter, r *http.Request)
	// GetEntry Fetch one posted entry with its lines
	// (GET /entries/{id})
	GetEntry(w http.ResponseWriter, r *http.Request, id string)
	// GetHealthz Liveness + DB connectivity
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// SyncPull Pull server changes since a watermark (WatermelonDB native protocol)
	// (POST /sync/pull)
	SyncPull(w http.ResponseWriter, r *http.Request)
	// SyncPush Push local changes to the server (WatermelonDB native protocol)
	// (POST /sync/push)
	SyncPush(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListAccounts List the user's accounts (pockets and categories)
// (GET /accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateAccount Create a pocket or category (chart-of-accounts entry)
// (POST /accounts)
func (_ Unimplemented) CreateAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAccountBalance Account debit/credit totals and normal-balance-signed amount
// (GET /accounts/{id}/balance)
func (_ Unimplemented) GetAccountBalance(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GoogleAuth Exchange a Google authorization code for a session
// (POST /auth/google)
func (_ Unimplemented) GoogleAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Exchange credentials for a session
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Revoke the presented refresh token
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Current authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotate a refresh token into a new session
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register Create a credential account and start a session
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListBudgets List budgets for a month, with spent amounts
// (GET /budgets)
func (_ Unimplemented) ListBudgets(w http.ResponseWriter, r *http.Request, params ListBudgetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SetBudget Create or update a monthly category budget
// (POST /budgets)
func (_ Unimplemented) SetBudget(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteBudget Delete a budget
// (DELETE /budgets/{id})
func (_ Unimplemented) DeleteBudget(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateBudget Update a budget's target
// (PUT /budgets/{id})
func (_ Unimplemented) UpdateBudget(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEntries List posted entries with their lines
// (GET /entries)
func (_ Unimplemented) ListEntries(w http.ResponseWriter, r *http.Request, params ListEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostEntry Post a balanced double-entry transaction
// (POST /entries)
func (_ Unimplemented) PostEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetEntry Fetch one posted entry with its lines
// (GET /entries/{id})
func (_ Unimplemented) GetEntry(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthz Liveness + DB connectivity
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SyncPull Pull server changes since a watermark (WatermelonDB native protocol)
// (POST /sync/pull)
func (_ Unimplemented) SyncPull(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SyncPush Push local changes to the server (WatermelonDB native protocol)
// (POST /sync/push)
func (_ Unimplemented) SyncPush(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBalance operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleAuth operation middleware
func (siw *ServerInterfaceWrapper) GoogleAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBudgets operation middleware
func (siw *ServerInterfaceWrapper) ListBudgets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBudgetsParams

	// ------------- Required query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "month"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBudgets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetBudget operation middleware
func (siw *ServerInterfaceWrapper) SetBudget(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetBudget(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBudget operation middleware
func (siw *ServerInterfaceWrapper) DeleteBudget(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBudget(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBudget operation middleware
func (siw *ServerInterfaceWrapper) UpdateBudget(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBudget(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEntries operation middleware
func (siw *ServerInterfaceWrapper) ListEntries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEntriesParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEntry operation middleware
func (siw *ServerInterfaceWrapper) PostEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntry operation middleware
func (siw *ServerInterfaceWrapper) GetEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncPull operation middleware
func (siw *ServerInterfaceWrapper) SyncPull(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncPull(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncPush operation middleware
func (siw *ServerInterfaceWrapper) SyncPush(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncPush(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/google", wrapper.GoogleAuth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/{id}/balance", wrapper.GetAccountBalance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries", wrapper.ListEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/entries", wrapper.PostEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries/{id}", wrapper.GetEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/budgets", wrapper.ListBudgets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/budgets", wrapper.SetBudget)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/budgets/{id}", wrapper.DeleteBudget)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/budgets/{id}", wrapper.UpdateBudget)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync/pull", wrapper.SyncPull)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync/push", wrapper.SyncPush)
	})

	return r
}

type ListAccountsRequestObject struct {
	Params ListAccountsParams
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse []Account

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts401JSONResponse Error

func (response ListAccounts401JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse Account

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse Error

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse Error

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount409JSONResponse Error

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountBalanceRequestObject struct {
	Id string `json:"id"`
}

type GetAccountBalanceResponseObject interface {
	VisitGetAccountBalanceResponse(w http.ResponseWriter) error
}

type GetAccountBalance200JSONResponse AccountBalance

func (response GetAccountBalance200JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountBalance401JSONResponse Error

func (response GetAccountBalance401JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountBalance404JSONResponse Error

func (response GetAccountBalance404JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuthRequestObject struct {
	Body *GoogleAuthJSONRequestBody
}

type GoogleAuthResponseObject interface {
	VisitGoogleAuthResponse(w http.ResponseWriter) error
}

type GoogleAuth200JSONResponse AuthResponse

func (response GoogleAuth200JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuth400JSONResponse Error

func (response GoogleAuth400JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuth401JSONResponse Error

func (response GoogleAuth401JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuth503JSONResponse Error

func (response GoogleAuth503JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse Error

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse Error

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
	Body *RefreshJSONRequestBody
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200JSONResponse AuthResponse

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401JSONResponse Error

func (response Refresh401JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse AuthResponse

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse Error

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse Error

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListBudgetsRequestObject struct {
	Params ListBudgetsParams
}

type ListBudgetsResponseObject interface {
	VisitListBudgetsResponse(w http.ResponseWriter) error
}

type ListBudgets200JSONResponse []BudgetWithSpent

func (response ListBudgets200JSONResponse) VisitListBudgetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBudgets401JSONResponse Error

func (response ListBudgets401JSONResponse) VisitListBudgetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetBudgetRequestObject struct {
	Body *SetBudgetJSONRequestBody
}

type SetBudgetResponseObject interface {
	VisitSetBudgetResponse(w http.ResponseWriter) error
}

type SetBudget201JSONResponse Budget

func (response SetBudget201JSONResponse) VisitSetBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SetBudget400JSONResponse Error

func (response SetBudget400JSONResponse) VisitSetBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetBudget401JSONResponse Error

func (response SetBudget401JSONResponse) VisitSetBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteBudgetRequestObject struct {
	Id string `json:"id"`
}

type DeleteBudgetResponseObject interface {
	VisitDeleteBudgetResponse(w http.ResponseWriter) error
}

type DeleteBudget204Response struct {
}

func (response DeleteBudget204Response) VisitDeleteBudgetResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteBudget401JSONResponse Error

func (response DeleteBudget401JSONResponse) VisitDeleteBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteBudget404JSONResponse Error

func (response DeleteBudget404JSONResponse) VisitDeleteBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBudgetRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateBudgetJSONRequestBody
}

type UpdateBudgetResponseObject interface {
	VisitUpdateBudgetResponse(w http.ResponseWriter) error
}

type UpdateBudget200JSONResponse Budget

func (response UpdateBudget200JSONResponse) VisitUpdateBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBudget401JSONResponse Error

func (response UpdateBudget401JSONResponse) VisitUpdateBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBudget404JSONResponse Error

func (response UpdateBudget404JSONResponse) VisitUpdateBudgetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListEntriesRequestObject struct {
	Params ListEntriesParams
}

type ListEntriesResponseObject interface {
	VisitListEntriesResponse(w http.ResponseWriter) error
}

type ListEntries200JSONResponse []Entry

func (response ListEntries200JSONResponse) VisitListEntriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEntries401JSONResponse Error

func (response ListEntries401JSONResponse) VisitListEntriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntryRequestObject struct {
	Body *PostEntryJSONRequestBody
}

type PostEntryResponseObject interface {
	VisitPostEntryResponse(w http.ResponseWriter) error
}

type PostEntry201JSONResponse Entry

func (response PostEntry201JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntry400JSONResponse Error

func (response PostEntry400JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntry401JSONResponse Error

func (response PostEntry401JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntry422JSONResponse Error

func (response PostEntry422JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntryRequestObject struct {
	Id string `json:"id"`
}

type GetEntryResponseObject interface {
	VisitGetEntryResponse(w http.ResponseWriter) error
}

type GetEntry200JSONResponse Entry

func (response GetEntry200JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntry401JSONResponse Error

func (response GetEntry401JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntry404JSONResponse Error

func (response GetEntry404JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse HealthStatus

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPullRequestObject struct {
	Body *SyncPullJSONRequestBody
}

type SyncPullResponseObject interface {
	VisitSyncPullResponse(w http.ResponseWriter) error
}

type SyncPull200JSONResponse SyncPullResponse

func (response SyncPull200JSONResponse) VisitSyncPullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPull401JSONResponse Error

func (response SyncPull401JSONResponse) VisitSyncPullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPushRequestObject struct {
	Body *SyncPushJSONRequestBody
}

type SyncPushResponseObject interface {
	VisitSyncPushResponse(w http.ResponseWriter) error
}

type SyncPush200JSONResponse SyncPushResponse

func (response SyncPush200JSONResponse) VisitSyncPushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPush401JSONResponse Error

func (response SyncPush401JSONResponse) VisitSyncPushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPush422JSONResponse Error

func (response SyncPush422JSONResponse) VisitSyncPushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAccounts List the user's accounts (pockets and categories)
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// CreateAccount Create a pocket or category (chart-of-accounts entry)
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// GetAccountBalance Account debit/credit totals and normal-balance-signed amount
	// (GET /accounts/{id}/balance)
	GetAccountBalance(ctx context.Context, request GetAccountBalanceRequestObject) (GetAccountBalanceResponseObject, error)
	// GoogleAuth Exchange a Google authorization code for a session
	// (POST /auth/google)
	GoogleAuth(ctx context.Context, request GoogleAuthRequestObject) (GoogleAuthResponseObject, error)
	// Login Exchange credentials for a session
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Revoke the presented refresh token
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetMe Current authenticated user
	// (GET /auth/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Refresh Rotate a refresh token into a new session
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Register Create a credential account and start a session
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// ListBudgets List budgets for a month, with spent amounts
	// (GET /budgets)
	ListBudgets(ctx context.Context, request ListBudgetsRequestObject) (ListBudgetsResponseObject, error)
	// SetBudget Create or update a monthly category budget
	// (POST /budgets)
	SetBudget(ctx context.Context, request SetBudgetRequestObject) (SetBudgetResponseObject, error)
	// DeleteBudget Delete a budget
	// (DELETE /budgets/{id})
	DeleteBudget(ctx context.Context, request DeleteBudgetRequestObject) (DeleteBudgetResponseObject, error)
	// UpdateBudget Update a budget's target
	// (PUT /budgets/{id})
	UpdateBudget(ctx context.Context, request UpdateBudgetRequestObject) (UpdateBudgetResponseObject, error)
	// ListEntries List posted entries with their lines
	// (GET /entries)
	ListEntries(ctx context.Context, request ListEntriesRequestObject) (ListEntriesResponseObject, error)
	// PostEntry Post a balanced double-entry transaction
	// (POST /entries)
	PostEntry(ctx context.Context, request PostEntryRequestObject) (PostEntryResponseObject, error)
	// GetEntry Fetch one posted entry with its lines
	// (GET /entries/{id})
	GetEntry(ctx context.Context, request GetEntryRequestObject) (GetEntryResponseObject, error)
	// GetHealthz Liveness + DB connectivity
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// SyncPull Pull server changes since a watermark (WatermelonDB native protocol)
	// (POST /sync/pull)
	SyncPull(ctx context.Context, request SyncPullRequestObject) (SyncPullResponseObject, error)
	// SyncPush Push local changes to the server (WatermelonDB native protocol)
	// (POST /sync/push)
	SyncPush(ctx context.Context, request SyncPushRequestObject) (SyncPushResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	var request ListAccountsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccountBalance operation middleware
func (sh *strictHandler) GetAccountBalance(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAccountBalanceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountBalance(ctx, request.(GetAccountBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountBalanceResponseObject); ok {
		if err := validResponse.VisitGetAccountBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GoogleAuth operation middleware
func (sh *strictHandler) GoogleAuth(w http.ResponseWriter, r *http.Request) {
	var request GoogleAuthRequestObject

	var body GoogleAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GoogleAuth(ctx, request.(GoogleAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GoogleAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GoogleAuthResponseObject); ok {
		if err := validResponse.VisitGoogleAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var request RefreshRequestObject

	var body RefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBudgets operation middleware
func (sh *strictHandler) ListBudgets(w http.ResponseWriter, r *http.Request, params ListBudgetsParams) {
	var request ListBudgetsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBudgets(ctx, request.(ListBudgetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBudgets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBudgetsResponseObject); ok {
		if err := validResponse.VisitListBudgetsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetBudget operation middleware
func (sh *strictHandler) SetBudget(w http.ResponseWriter, r *http.Request) {
	var request SetBudgetRequestObject

	var body SetBudgetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetBudget(ctx, request.(SetBudgetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetBudget")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetBudgetResponseObject); ok {
		if err := validResponse.VisitSetBudgetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteBudget operation middleware
func (sh *strictHandler) DeleteBudget(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteBudgetRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBudget(ctx, request.(DeleteBudgetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBudget")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteBudgetResponseObject); ok {
		if err := validResponse.VisitDeleteBudgetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateBudget operation middleware
func (sh *strictHandler) UpdateBudget(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateBudgetRequestObject

	request.Id = id

	var body UpdateBudgetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBudget(ctx, request.(UpdateBudgetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBudget")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateBudgetResponseObject); ok {
		if err := validResponse.VisitUpdateBudgetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEntries operation middleware
func (sh *strictHandler) ListEntries(w http.ResponseWriter, r *http.Request, params ListEntriesParams) {
	var request ListEntriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEntries(ctx, request.(ListEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEntries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEntriesResponseObject); ok {
		if err := validResponse.VisitListEntriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEntry operation middleware
func (sh *strictHandler) PostEntry(w http.ResponseWriter, r *http.Request) {
	var request PostEntryRequestObject

	var body PostEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEntry(ctx, request.(PostEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEntryResponseObject); ok {
		if err := validResponse.VisitPostEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntry operation middleware
func (sh *strictHandler) GetEntry(w http.ResponseWriter, r *http.Request, id string) {
	var request GetEntryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntry(ctx, request.(GetEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntryResponseObject); ok {
		if err := validResponse.VisitGetEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncPull operation middleware
func (sh *strictHandler) SyncPull(w http.ResponseWriter, r *http.Request) {
	var request SyncPullRequestObject

	var body SyncPullJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncPull(ctx, request.(SyncPullRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncPull")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncPullResponseObject); ok {
		if err := validResponse.VisitSyncPullResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncPush operation middleware
func (sh *strictHandler) SyncPush(w http.ResponseWriter, r *http.Request) {
	var request SyncPushRequestObject

	var body SyncPushJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncPush(ctx, request.(SyncPushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncPush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncPushResponseObject); ok {
		if err := validResponse.VisitSyncPushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fxfc+M2kv8qXbyril2RLI3jZHN27cP8SzK5zG7KM1O5q2jKA5MtCRkSYADQtjblqnvc5637hPkkV90A",
	"KFIi9WfWdjKXfZNEEGj03183GvolSXVRaoXK2eT0l8SmcywEf3ycprpSjj6WRpdonER+IEw6l1eY0We3",
	"KDE5TS61zlGo5HaQpAaFw+xC8JtTbQr6lGTC4dDJApNBfMk6I9WM36mMQZUu6I0MbWpk6aRWyWny4tVf",
	"4eT40Z8gDoFUZzQH3oiizGmaF8/Ou+aU2fpsaS5RueEMFRoiEmQGBz8Ih6bAXKtnTw5BG7BortBAVcms",
	"a2IlCmxsffmgFAaVu+haWPMHkYMfA8LzFg6cQYS51u/PoFKVJZIUvDw+TAaJqvJcXNIWnamwgxD/wy/J",
	"vxucJqfJv42WohwFOY6CEF/T0NtBUpXZnsK5HSQGf66kIXn/mCxZ0pBa4MlgqRktNWgt+7ZeQV/+hKkj",
	"qgKRT0QuVIodCuefB86ua4/BTLqLQiptWtuSyn1xstySVA5naFYVbqsmZXi55/RWzhRmy1fayqBognx4",
	"6bc79INBFF4jhLXoRnhTorIIfwZe/de//8Pv8gy0m6Ox8GfwP/z693/wiMMzKLWVTl4hSAtzFLmbL0Z+",
	"rWSwneoVQTd43pJ0kxkrrF/Z9wZJvw6a2+bL07kwbqinw7C2BXr/CDxHcikuZS7dAoRBKHX6Hp09A6lS",
	"XWDk14h2EIakwuFMG4n2iPyFqgreF02WDJJ6umSQ+DnYqfAs9InnaexhqQ6PKzc/R1tqGtmlq2jthdPv",
	"Ua1v0c61ccOcbAS+eXX8+Rfw7Q+vz8CiykBYeEdzayP/Jmj8KTxBYdDApBqPP0t5Sv6I77rU1ODUoJ33",
	"Li3VLMdhZRF0KX6uEHjgGRjthEO4kgJGonLzUZioa43Kotnmct7YbnVasmWV1jBvl8I8qbIZug9xCf9U",
	"ENoxuqyHADRSZxeFVm6+tnLXPE6YGe7nXO7Gh7fsu0X2ClEt69/Hq3vR/SDd/FWJ6v+xDC1tr8/Zi9RV",
	"Igcak0k1A6thKgy4ubQQ+b2D0D8GPWny4YO15rlyZrGuK/euDNObC4KEHZjRaGuHNfykQXDw8uTwDAig",
	"wZQAo3et9RhUjsLOLhhuV5S6HZbmUnlWSYeF3eakv9WVUSL/TipcQslEGCMW9L3AQncah9WV8RAtBtRC",
	"qIoRhkFiAI0bJLIotXGd4dM64SrbnCEzYkqaUWrrMOt8yd2oiyyIZ6s93hHIjUvWJLd0OjAisCqyf09d",
	"N8Zb84quU4azHr8dKRIUIp1LhZwGsfKxJ0GaCdJcWNvKjaS6ErnMLginoXJS5LaLYwVaK2Ydi86rQqih",
	"QZHx4hk6IfOuFWDjCiv8DSlcXLWLNV9rPcvxHH+u0LpdWSSa6ClwyOgC8KbUQ3o4tGgtje2ET5k0mLqL",
	"ysj1qd0cIY6AN+cvgH4QZQkxZ+PvlZuDCTTvyITWsl2c+IaR/KvaatqMyC7Xaf1eWzczaCHVSmHq5JWH",
	"udHeqpJwvL5WtN5SkvzzBnNtL1IaTYgOCMsqXFE7/X7r9mubyi47t910UPsiB59K9UXkSoWMK8RK4HFQ",
	"KeksHKTkJg9BOJZoNPhPLNhU5K3Cw+fj8Xg8uPtsM235Rkq36kSr0zdStFn0sWLH+LKbS6xXWoEFWZqs",
	"ML2x5y7hklRfqLJy9yXahki78FUhlSyIwY+2iau7jHMGGU5FlVOKqllRmDXLItXByxMoqtzJJSiwVUkx",
	"8XCX2tXeOrCx5uTlDTI7ixgiit6CYDwB13NUoAvpHG7XhS2y7xS4nknV682xoKjSjNX+l0FXjc3aa22y",
	"1uj6x22Ux2nrF7po/QtehzJFf/jZP824G9nAwfnzV6+hFG5+uKk2WYib71DNKIH5csz6Hr8+GmwpXN59",
	"2XFFCD3Vwx5R+CyyVxJb3MX92sV6rtheaSqNdZCJBegpewkeB3g0O4Lj8fEXw/GfhuNHTQe1a5mgvc4l",
	"82hZQ5RqmwPcp/i3KenrERoncXdjPb152VKM6wnamRecRTdgvodSKxBYNVIQiyygmmqTMg4YEpKjpK7l",
	"nB9RhD8aj39ro94vs1vG1ls2/Bf+peMHTfKa+dpOIVRnYrHdEFYh9NKFeB51qeO5LzX2auNa2XTzmu3h",
	"3QvOpHVoele8FBYv9gUZQZGePH71/OLpm/Pz5395+t8Xz55/9fjNd693gRR3GGMb0eTLO4m4rxYqfToX",
	"ahZ8epZJz4LvW3zbpPU0xWsKW3EePrdpsrUQJbthTmQp4sDQF9Mh9a8MKF+i/Uo1I443zwWhNNrpVDf4",
	"1Sb/+yrPewWeC+suyirP66LESmrvZetkgdaJoozhgt4DW3HpfFrlQFOcwZjTfqkkJdtgFyr9AA+/QtLb",
	"jdvqO+tIlzLbJpuGWOptbmfEWXSlFlVmfalDWGgTD9pn3wpvHLPoA9gRd9Kkrp8nG7zJh7Ckh5bN6/fJ",
	"hCtBXfk6mqHBVJssFItC9cWyNvknxGHhINVVnoHSDi65xpFLilEnx8eALqUIVcehHmwYQ8xtzw5ahtpX",
	"6m0FvLVpVmNZhjn2vNRHXV2e22elri294Wm2ANW9C/irqHkb7HoTjub2ijUf3l7xIQX5PWKQbEef7qJ3",
	"Z40izNjeeIvede4R5iFgI93iFVlo4B2fvj6uPLT3376KFH37A4VdtmdugOGnSxLnzpXJLU0s1VR31OjQ",
	"WMaKU6kYmma6usxx6OsIOWYzNEfw8hGIjM0yFBdtZaYixYk6MAFljHJKreOZ7WjGdVP4lAMWpoQuC6Qx",
	"unKHRxDyMjuIZxSDiWLoNACfRNgBTG8GUMM8+kgojz8KlXG8gZw+SQU5hUgoZI7WaYX2bKKI1K9ruELa",
	"zBQT4Da4LDlxXZb9+VTm/vD5XSHeIyHld0cTrtBKxwr4FXNIPs7zBTz+/kUySK7QWM/G8dHx0Zj0RZeo",
	"RCmT0+Szo/HRZ4w43JzFOIrtBPQlHCaTiXCV+EWWnCbfSesiZ/hNIwp0SG70x18SSQv9XKGpU9XTmMN6",
	"d75fMvyWlNZ7b6boeDz2FW3lwikpu9yUyRv9ZLVa9mXtnATE3q11/7WGi0StEhF45gsSikODGVwuuAmD",
	"JjoZP9qL0E30+ZOPDmoKaS3hL0Y4/mTBI+2mjbJYmtb541tiq62KQphFECgbTWXRfGKhbig5CH0jrMrL",
	"BhFOu8TMMjJi20ve3voDqXVtecqeJHLYuyC07onOFnfGn/Ua1G3b2zlT4e2aJt2dgGoF6lUYiHGaVWP8",
	"AKohcooHpJQ6W7Q0ZFHiKPr6EZvob6+vRMB/3D8BQtXNhJw1SN81BdfSzf1XznVEblBkC8AbaZ3dz5q8",
	"woMITVe012A6CzhI15q2OIR1WtTtYOmMR7/I7HZ0uWz56/TMX6NbaQ7sds/k7JfemYFA21aavnoVRfyz",
	"HnkHO4rUbzCnyIrfh+aePIDmho1TojHVlcr208rAWd8fOfJnI+C0E7n37pu6LHuVs3IRQjGUDv6/Tfdr",
	"LuReEmwRZQmmUkuAVp8+D/3pc66vGdusnUATiRMV01oEg7bKCWVBxyH2p9A8JYY5GjwCIsOjrIkymCEW",
	"fiZ+40ByidN/V1MZjuZjOj3XOTcjebBG250o/+jCYmrQHQ7gCo2cSvSTMKr2AHAqVTbUZujdv63D7BF8",
	"/59Pn4O0EyVZbSKWIPlWFrPTJXnSAt74PDcLmxhamdVei3ZGZAwmyvL5muF3lObXLwJpxh++kWPziHHF",
	"d/DGWHnuJ0i3exR2CtB36FiaXagd1hX17LeN0g/mzVitDP7kUx5tvMZCpYKuMAM+H392/5SEDExzvka6",
	"zwY4qwhNh0qV13jv7mp/9jwYBIhgkl2eYKoNCGh0sQQvRkObPoyTwqYLW0l4+PH9WEXrqPdjMIoH0M6u",
	"Jqke6TeG7CNtHXop+sRNz+9H3ivnKztJ/KSjwYqwBxi80u8fUDB3k26eM9Vs2qVBi4p8UKjIQGxx7xNe",
	"sRH9vvQ9YvdkL6FVf40tEc6QIqZcr+EG/Y9LKk85IXRdG+mXRrz7sBH99QjZ17hYgRkpCfAP/d2HT+PY",
	"UkgzUTzWVUZhdgSPwWCZiwVmA4KKZDoD2v1UG0JIfvaFxDyzcDJ+FO5sSK14HuF0IdMBWA0GK8tQKcNQ",
	"/atDTqpVFinnd7sw03l99eP34ioeLjj4ezBZ7W8fStuD7nhFb8s/Zu0En1cCxrm/tSNWVVA5DQIUXu8Q",
	"N2INuT9yxLPse1OI9lH5vzB0T6XrGsV7qM/QH6q25DF0VMKoLWuqWNeHltilrknxkYETxm0DMuH4YWON",
	"/kkYs1OJPvYr9deB7qdZ62EK/KuXq3Yo9AcOh0sDcX+ccfPNHTA6z6vyYyz1N7cm/MYGzZ35qo9taJ5/",
	"Y0OV/xUGdbu/Cn/7xPiBC/xhc716Ahbd76C0H/zIsrrvzfojQ6LeQWoDvuMg6mi+WBbSL6OyrWlowzty",
	"0dy7rhx9d11ba5/x77XiPkCp/KSvHRViS8YfpqAd9v2B9WwvOhAbNGGQhCsTbaE3+0/uTeh37wG72mYe",
	"GABudYKxQ+hfOryTDr+J7s1P84kF37bU59biRdlNoO95fZl2B9A3Nbpo9WVsbSju6e/Qe83yIJDP34ze",
	"AegFrlISiNYNPbAlNBSuKdZ96iwsI9Tso+zv8NeFYyNTfXQkDcS7uBtaOtpU/WBkPMryDVhzFBkazl6k",
	"s/FsNvMzg1SgFYIzQlmRci0FXs9xotbvGRzYqqCEgk8pLfwZwnd/XmkHUKKpm+8O+fSsvpdwqd08XE6I",
	"YmCKLhcgoL7k6YyczdCcgVBQRQoymoY2EotGx8dH/EqDYcIgyKKofEf0r//zv5Bqw/dbmZViogxyp5Wa",
	"ea4MQNEPtBARfwQvj+OtNtt3B/5solbuZxx89V+HNQ2xkezlSVc1igj2Wn9vGLx1U+WBIXgw6G4DXgT9",
	"/h1gcG9Ov4sQeHz8AFUP5j4fN9ddGXvGQVJcioLRbbSaOxtuo68PIZhHDff7TgeicXxULTG9al+73z8O",
	"3PIa8YFo6yt06ZwjUSMULrz3pmDTGwZJxfwfhP2toV1tys75cMLC8XjsZ3yXXZ5OkqqcJO/87bU6Agll",
	"r9HYAXw+/qw5NtPXapK8mygeLh1kGtmqfPNKo4emshhudzjtz8tNES7upe+RQoSlaCTSOceqS5xqgyCc",
	"w6L0TTPcl9zZBYLum7DVe9Tp1p80dMg5/B3bXTchbFs2E05cCotQLbm3Urz9Lvx/A3wKz56s/mNE1By7",
	"sA6LoDnE6RHfs+k9JGtenfrEghL8t3T0zqis7Ly+TdVShNLoK5mhnaiV+z0HpAmty1Gs3R2Xow7PGv0V",
	"pDFeh0We1zdcQi1/EFM7PmexeuqGoV4BYurQ+JswhS5QucFEzYyuytAOTUxsEV6gmXn0aNEfwDB9OhV5",
	"6xLZRFmnDR7B86J0i2G454MOarVkTOYb1+BAaULsM6j7pCRBS0c4k/fOG+5S+Xhx655Q0+p1twfO2deu",
	"pXV1AwWWRaGviu8jS3dou/FGRdCaoA0CrlnBhHnf/iPT2uaCpR22rFmlbVvedODdmtU3LBKy4dAzjeY0",
	"CtY0ikYUOH/m9TXQHv4zxttKwblMbaJ8ZFkbubevSLxvKsywKDXJ6hQMkqwWsYXRigIDSSHfUdrfcltN",
	"eiaqnfUQCT5n7LwiLqxF49o9ipRoTdQy0wpRN27k5Pg4zhr9wzQXM0vxb6oN9x+AwSuJ1/22e28n8Kv3",
	"F38T27UbD105QIg0xZK9c0stmIPLe55/mJSkQ9t8p+O+fsTOQ1yKbiT8fU0w0L1dCK9Or/rEo021XynD",
	"q2SQVCYPt+JORyN+MNfWnX45/nKcEJFh4tUpPMDhP0A9/gJqUxE5oMpKLf2hXshxAkq5Haxj2Zm0zr86",
	"AO6NHEBsOOPuiQH8lVg2aJxRh0n5iHp9ymfNjE6s3apjFxDxd5gpwO/1uV52nwU1Xg1F0/VX23fUa3yl",
	"p1NaPF4Or/mj0uT27e3/BQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
