// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountType.
const (
	Asset     AccountType = "asset"
	Equity    AccountType = "equity"
	Expense   AccountType = "expense"
	Income    AccountType = "income"
	Liability AccountType = "liability"
)

// Valid indicates whether the value is a known member of the AccountType enum.
func (e AccountType) Valid() bool {
	switch e {
	case Asset:
		return true
	case Equity:
		return true
	case Expense:
		return true
	case Income:
		return true
	case Liability:
		return true
	default:
		return false
	}
}

// Defines values for EntrySource.
const (
	EntrySourceImport    EntrySource = "import"
	EntrySourceManual    EntrySource = "manual"
	EntrySourceRecurring EntrySource = "recurring"
)

// Valid indicates whether the value is a known member of the EntrySource enum.
func (e EntrySource) Valid() bool {
	switch e {
	case EntrySourceImport:
		return true
	case EntrySourceManual:
		return true
	case EntrySourceRecurring:
		return true
	default:
		return false
	}
}

// Defines values for EntryStatus.
const (
	Draft  EntryStatus = "draft"
	Posted EntryStatus = "posted"
)

// Valid indicates whether the value is a known member of the EntryStatus enum.
func (e EntryStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusDb.
const (
	Down HealthStatusDb = "down"
	Up   HealthStatusDb = "up"
)

// Valid indicates whether the value is a known member of the HealthStatusDb enum.
func (e HealthStatusDb) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for JournalLineDc.
const (
	JournalLineDcCredit JournalLineDc = "credit"
	JournalLineDcDebit  JournalLineDc = "debit"
)

// Valid indicates whether the value is a known member of the JournalLineDc enum.
func (e JournalLineDc) Valid() bool {
	switch e {
	case JournalLineDcCredit:
		return true
	case JournalLineDcDebit:
		return true
	default:
		return false
	}
}

// Defines values for LineInputDc.
const (
	LineInputDcCredit LineInputDc = "credit"
	LineInputDcDebit  LineInputDc = "debit"
)

// Valid indicates whether the value is a known member of the LineInputDc enum.
func (e LineInputDc) Valid() bool {
	switch e {
	case LineInputDcCredit:
		return true
	case LineInputDcDebit:
		return true
	default:
		return false
	}
}

// Defines values for NewEntryRequestSource.
const (
	NewEntryRequestSourceImport    NewEntryRequestSource = "import"
	NewEntryRequestSourceManual    NewEntryRequestSource = "manual"
	NewEntryRequestSourceRecurring NewEntryRequestSource = "recurring"
)

// Valid indicates whether the value is a known member of the NewEntryRequestSource enum.
func (e NewEntryRequestSource) Valid() bool {
	switch e {
	case NewEntryRequestSourceImport:
		return true
	case NewEntryRequestSourceManual:
		return true
	case NewEntryRequestSourceRecurring:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Archived  bool      `json:"archived"`
	CreatedAt time.Time `json:"created_at"`

	// Currency ISO 4217 currency code
	//
	// Example: IDR
	Currency string `json:"currency"`

	// Id client-generated id (WatermelonDB) or server uuid
	Id   string `json:"id"`
	Name string `json:"name"`

	// ParentId optional parent account (tree hook; unused in M2)
	ParentId *string `json:"parent_id,omitempty"`

	// Type Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
	Type      AccountType `json:"type"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// AccountBalance defines model for AccountBalance.
type AccountBalance struct {
	AccountId   string `json:"account_id"`
	CreditMinor int64  `json:"credit_minor"`

	// Currency Example: IDR
	Currency   string `json:"currency"`
	DebitMinor int64  `json:"debit_minor"`

	// SignedMinor normal-balance-signed amount (asset/expense = debit−credit; others = credit−debit); positive is healthy/normal
	SignedMinor int64 `json:"signed_minor"`
}

// AccountType Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
type AccountType string

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken short-lived HS256 JWT; send as `Authorization: Bearer <token>`
	AccessToken string `json:"access_token"`

	// RefreshToken single-use opaque token; rotate via /auth/refresh
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// Entry defines model for Entry.
type Entry struct {
	CreatedAt time.Time `json:"created_at"`

	// Currency Example: IDR
	Currency string `json:"currency"`

	// FxRate cross-currency rate (M4); null for single-currency entries
	FxRate *string `json:"fx_rate,omitempty"`

	// Id client-generated id or server uuid
	Id        string             `json:"id"`
	Lines     []JournalLine      `json:"lines"`
	Memo      string             `json:"memo"`
	Source    EntrySource        `json:"source"`
	Status    EntryStatus        `json:"status"`
	TxnDate   openapi_types.Date `json:"txn_date"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// EntrySource defines model for Entry.Source.
type EntrySource string

// EntryStatus defines model for Entry.Status.
type EntryStatus string

// Error defines model for Error.
type Error struct {
	// Code stable machine code for this error class
	//
	// Example: invalid_credentials
	Code string `json:"code"`

	// Message human-readable detail
	//
	// Example: invalid credentials
	Message string `json:"message"`
}

// GoogleRequest defines model for GoogleRequest.
type GoogleRequest struct {
	// Code authorization code from expo-auth-session
	Code string `json:"code"`

	// RedirectUri the redirect URI the app used in the auth request
	RedirectUri string `json:"redirect_uri"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Db Postgres connectivity
	//
	// Example: up
	Db HealthStatusDb `json:"db"`

	// Status process liveness
	//
	// Example: ok
	Status string `json:"status"`
}

// HealthStatusDb Postgres connectivity
//
// Example: up
type HealthStatusDb string

// JournalLine defines model for JournalLine.
type JournalLine struct {
	AccountId string `json:"account_id"`

	// AmountMinor unsigned integer minor units (cents) at the currency's scale
	//
	// Example: 50000
	AmountMinor int64 `json:"amount_minor"`

	// Currency Example: IDR
	Currency string        `json:"currency"`
	Dc       JournalLineDc `json:"dc"`
	EntryId  string        `json:"entry_id"`

	// Id client-generated id
	Id string `json:"id"`
}

// JournalLineDc defines model for JournalLine.Dc.
type JournalLineDc string

// LineInput defines model for LineInput.
type LineInput struct {
	AccountId string `json:"account_id"`

	// AmountMinor unsigned minor units
	AmountMinor int64 `json:"amount_minor"`

	// Currency optional; defaults to the entry currency (M4 multi-currency support)
	//
	// Example: IDR
	Currency *string     `json:"currency,omitempty"`
	Dc       LineInputDc `json:"dc"`

	// Id optional client id; server generates a uuid when omitted
	Id *string `json:"id,omitempty"`
}

// LineInputDc defines model for LineInput.Dc.
type LineInputDc string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NewAccountRequest defines model for NewAccountRequest.
type NewAccountRequest struct {
	// Currency Example: IDR
	Currency string `json:"currency"`

	// Id optional client id; server generates a uuid when omitted (REST path)
	Id       *string `json:"id,omitempty"`
	Name     string  `json:"name"`
	ParentId *string `json:"parent_id,omitempty"`

	// Type Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
	Type AccountType `json:"type"`
}

// NewEntryRequest defines model for NewEntryRequest.
type NewEntryRequest struct {
	// Currency Example: IDR
	Currency string `json:"currency"`

	// FxRate optional cross-currency rate; when set, the balance invariant is enforced in-app (M4)
	//
	// Example: 15000.00
	FxRate *string `json:"fx_rate,omitempty"`

	// Id optional client id; server generates a uuid when omitted (REST path)
	Id     *string                `json:"id,omitempty"`
	Lines  []LineInput            `json:"lines"`
	Memo   *string                `json:"memo,omitempty"`
	Source *NewEntryRequestSource `json:"source,omitempty"`

	// TxnDate optional; defaults to today
	TxnDate *openapi_types.Date `json:"txn_date,omitempty"`
}

// NewEntryRequestSource defines model for NewEntryRequest.Source.
type NewEntryRequestSource string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// BaseCurrency optional; defaults to server BASE_CURRENCY_DEFAULT
	//
	// Example: IDR
	BaseCurrency *string             `json:"base_currency,omitempty"`
	Email        openapi_types.Email `json:"email"`
	Password     string              `json:"password"`
}

// User defines model for User.
type User struct {
	// BaseCurrency ISO 4217 currency code
	//
	// Example: IDR
	BaseCurrency string              `json:"base_currency"`
	CreatedAt    time.Time           `json:"created_at"`
	Email        openapi_types.Email `json:"email"`
	Id           openapi_types.UUID  `json:"id"`
}

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	Type *AccountType `form:"type,omitempty" json:"type,omitempty"`
}

// ListEntriesParams defines parameters for ListEntries.
type ListEntriesParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = NewAccountRequest

// GoogleAuthJSONRequestBody defines body for GoogleAuth for application/json ContentType.
type GoogleAuthJSONRequestBody = GoogleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// PostEntryJSONRequestBody defines body for PostEntry for application/json ContentType.
type PostEntryJSONRequestBody = NewEntryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAccounts List the user's accounts (pockets and categories)
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams)
	// CreateAccount Create a pocket or category (chart-of-accounts entry)
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// GetAccountBalance Account debit/credit totals and normal-balance-signed amount
	// (GET /accounts/{id}/balance)
	GetAccountBalance(w http.ResponseWriter, r *http.Request, id string)
	// GoogleAuth Exchange a Google authorization code for a session
	// (POST /auth/google)
	GoogleAuth(w http.ResponseWriter, r *http.Request)
	// Login Exchange credentials for a session
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Revoke the presented refresh token
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetMe Current authenticated user
	// (GET /auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Refresh Rotate a refresh token into a new session
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// Register Create a credential account and start a session
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// ListEntries List posted entries with their lines
	// (GET /entries)
	ListEntries(w http.ResponseWriter, r *http.Request, params ListEntriesParams)
	// PostEntry Post a balanced double-entry transaction
	// (POST /entries)
	PostEntry(w http.ResponseWriter, r *http.Request)
	// GetEntry Fetch one posted entry with its lines
	// (GET /entries/{id})
	GetEntry(w http.ResponseWriter, r *http.Request, id string)
	// GetHealthz Liveness + DB connectivity
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListAccounts List the user's accounts (pockets and categories)
// (GET /accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateAccount Create a pocket or category (chart-of-accounts entry)
// (POST /accounts)
func (_ Unimplemented) CreateAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAccountBalance Account debit/credit totals and normal-balance-signed amount
// (GET /accounts/{id}/balance)
func (_ Unimplemented) GetAccountBalance(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GoogleAuth Exchange a Google authorization code for a session
// (POST /auth/google)
func (_ Unimplemented) GoogleAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Exchange credentials for a session
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Revoke the presented refresh token
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Current authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotate a refresh token into a new session
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register Create a credential account and start a session
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEntries List posted entries with their lines
// (GET /entries)
func (_ Unimplemented) ListEntries(w http.ResponseWriter, r *http.Request, params ListEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostEntry Post a balanced double-entry transaction
// (POST /entries)
func (_ Unimplemented) PostEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetEntry Fetch one posted entry with its lines
// (GET /entries/{id})
func (_ Unimplemented) GetEntry(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthz Liveness + DB connectivity
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBalance operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleAuth operation middleware
func (siw *ServerInterfaceWrapper) GoogleAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEntries operation middleware
func (siw *ServerInterfaceWrapper) ListEntries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEntriesParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEntry operation middleware
func (siw *ServerInterfaceWrapper) PostEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntry operation middleware
func (siw *ServerInterfaceWrapper) GetEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/google", wrapper.GoogleAuth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/{id}/balance", wrapper.GetAccountBalance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries", wrapper.ListEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/entries", wrapper.PostEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries/{id}", wrapper.GetEntry)
	})

	return r
}

type ListAccountsRequestObject struct {
	Params ListAccountsParams
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse []Account

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts401JSONResponse Error

func (response ListAccounts401JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse Account

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse Error

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse Error

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount409JSONResponse Error

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountBalanceRequestObject struct {
	Id string `json:"id"`
}

type GetAccountBalanceResponseObject interface {
	VisitGetAccountBalanceResponse(w http.ResponseWriter) error
}

type GetAccountBalance200JSONResponse AccountBalance

func (response GetAccountBalance200JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountBalance401JSONResponse Error

func (response GetAccountBalance401JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountBalance404JSONResponse Error

func (response GetAccountBalance404JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuthRequestObject struct {
	Body *GoogleAuthJSONRequestBody
}

type GoogleAuthResponseObject interface {
	VisitGoogleAuthResponse(w http.ResponseWriter) error
}

type GoogleAuth200JSONResponse AuthResponse

func (response GoogleAuth200JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuth400JSONResponse Error

func (response GoogleAuth400JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuth401JSONResponse Error

func (response GoogleAuth401JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GoogleAuth503JSONResponse Error

func (response GoogleAuth503JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse Error

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse Error

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
	Body *RefreshJSONRequestBody
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200JSONResponse AuthResponse

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401JSONResponse Error

func (response Refresh401JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse AuthResponse

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse Error

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse Error

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListEntriesRequestObject struct {
	Params ListEntriesParams
}

type ListEntriesResponseObject interface {
	VisitListEntriesResponse(w http.ResponseWriter) error
}

type ListEntries200JSONResponse []Entry

func (response ListEntries200JSONResponse) VisitListEntriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEntries401JSONResponse Error

func (response ListEntries401JSONResponse) VisitListEntriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntryRequestObject struct {
	Body *PostEntryJSONRequestBody
}

type PostEntryResponseObject interface {
	VisitPostEntryResponse(w http.ResponseWriter) error
}

type PostEntry201JSONResponse Entry

func (response PostEntry201JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntry400JSONResponse Error

func (response PostEntry400JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntry401JSONResponse Error

func (response PostEntry401JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEntry422JSONResponse Error

func (response PostEntry422JSONResponse) VisitPostEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntryRequestObject struct {
	Id string `json:"id"`
}

type GetEntryResponseObject interface {
	VisitGetEntryResponse(w http.ResponseWriter) error
}

type GetEntry200JSONResponse Entry

func (response GetEntry200JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntry401JSONResponse Error

func (response GetEntry401JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntry404JSONResponse Error

func (response GetEntry404JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse HealthStatus

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAccounts List the user's accounts (pockets and categories)
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// CreateAccount Create a pocket or category (chart-of-accounts entry)
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// GetAccountBalance Account debit/credit totals and normal-balance-signed amount
	// (GET /accounts/{id}/balance)
	GetAccountBalance(ctx context.Context, request GetAccountBalanceRequestObject) (GetAccountBalanceResponseObject, error)
	// GoogleAuth Exchange a Google authorization code for a session
	// (POST /auth/google)
	GoogleAuth(ctx context.Context, request GoogleAuthRequestObject) (GoogleAuthResponseObject, error)
	// Login Exchange credentials for a session
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Revoke the presented refresh token
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetMe Current authenticated user
	// (GET /auth/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Refresh Rotate a refresh token into a new session
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Register Create a credential account and start a session
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// ListEntries List posted entries with their lines
	// (GET /entries)
	ListEntries(ctx context.Context, request ListEntriesRequestObject) (ListEntriesResponseObject, error)
	// PostEntry Post a balanced double-entry transaction
	// (POST /entries)
	PostEntry(ctx context.Context, request PostEntryRequestObject) (PostEntryResponseObject, error)
	// GetEntry Fetch one posted entry with its lines
	// (GET /entries/{id})
	GetEntry(ctx context.Context, request GetEntryRequestObject) (GetEntryResponseObject, error)
	// GetHealthz Liveness + DB connectivity
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	var request ListAccountsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccountBalance operation middleware
func (sh *strictHandler) GetAccountBalance(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAccountBalanceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountBalance(ctx, request.(GetAccountBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountBalanceResponseObject); ok {
		if err := validResponse.VisitGetAccountBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GoogleAuth operation middleware
func (sh *strictHandler) GoogleAuth(w http.ResponseWriter, r *http.Request) {
	var request GoogleAuthRequestObject

	var body GoogleAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GoogleAuth(ctx, request.(GoogleAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GoogleAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GoogleAuthResponseObject); ok {
		if err := validResponse.VisitGoogleAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var request RefreshRequestObject

	var body RefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEntries operation middleware
func (sh *strictHandler) ListEntries(w http.ResponseWriter, r *http.Request, params ListEntriesParams) {
	var request ListEntriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEntries(ctx, request.(ListEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEntries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEntriesResponseObject); ok {
		if err := validResponse.VisitListEntriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEntry operation middleware
func (sh *strictHandler) PostEntry(w http.ResponseWriter, r *http.Request) {
	var request PostEntryRequestObject

	var body PostEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEntry(ctx, request.(PostEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEntryResponseObject); ok {
		if err := validResponse.VisitPostEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntry operation middleware
func (sh *strictHandler) GetEntry(w http.ResponseWriter, r *http.Request, id string) {
	var request GetEntryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntry(ctx, request.(GetEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntryResponseObject); ok {
		if err := validResponse.VisitGetEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftfb9tGEv8qA94BtRHKUhynl7PRBydx2vSStnAS5A5V4KzIkbg1ucvsLm2rgYF77HNxn7Cf5DCzS0qU",
	"KFtqbTfB3ZskLmdnZ37zf/UxSnRRaoXK2Wj/Y2STDAvBHw+TRFfK0cfS6BKNk8gPhEkyeYYpfXbTEqP9",
	"aKR1jkJFl3GUGBQO0xPBb461KehTlAqHPScLjOL6JeuMVBN+pzIGVTKlN1K0iZGlk1pF+9HzV9/D3u79",
	"v0G9BBKdEg28EEWZE5nnT4+7aMp0mVqSS1SuN0GFhpgEmcLWW+HQFJhr9fTxNmgDFs0ZGqgqmXYRVqLA",
	"uaPPHpTCoHInXRtr/iBy8GtAeNnCljOIkGl9egCVqiyxpODl7nYUR6rKczGiIzpTYQcj/oeP0V8NjqP9",
	"6C/9mSr7QY/9oMTXtPQyjqoy3VA5l3Fk8EMlDen7x2gmkjmtBZnEM2S0YNDa9l2zgx79hIkjrgKTj0Uu",
	"VIIdgPPPg2SX0WMwle6kkEqb1rGkcl/uzY4klcMJmkXAXYukFEcbkrdyojCdvdIGgyICeW/kj9vzi0EU",
	"HhHCWnR9vChRWYSvgHf/7Zdf/SkPQLsMjYWvwP/w2y+/8ortAyi1lU6eIUgLGYrcZdO+3yuKr+d6QdFz",
	"Mm9pel4YC6JfOPcVmn4dkNuWy5NMGNfT417Y2wK9vwNeIrkUI5lLNwVhEEqdnKKzByBVogus5dWnE4Ql",
	"iXA40Uai3SF/oaqCz0XEojhqyEVx5GmwU2Eq9InpzJ1hBofDymXHaEtNK7uwitaeOH2KavmINtPG9XKy",
	"Efjm1e7DL+Hbt68PwKJKQVh4T7S1kT8LWr8Pj1EYNDCsBoMHCZPkj/i+C6YGxwZttnJrqSY59iqLoEvx",
	"oULghQdgtBMO4UwK6IvKZf1AqGuPyqK5zuW8sd1wmollkddAtwswR8qZ6bKU/2iQudbmxxcnFCE6QojR",
	"1vaaaESLYOvl3vYBkL+GMcUPL+lmDSpHKFzHpa8btK6PUrlUXlTSYWGv09m3ujJK5C+kwllkiYQxYkrf",
	"Cyx0p+u1ujLeY9f2VQhVscMxSAKgdXEki1Ib12lN1glX2XkKqRFjstBSW4dp50vuQp2kQT0t5Xdi9mZi",
	"Xr1lw3LLLQZBBFHV4t8sDB4Z48PFAtYp4Vk2Z0dAgkIkmVTIWRGDz2XSAhIlSHJhbStVkupM5DI9IbeN",
	"ykmR2y6JFWitmHRsmlWFUD2DIuXNU3RC5l07wJU7LMg3ZHT1rl2i+VrrSY7H+KFC69YVkZh3pkFCRheA",
	"F6Xu0cOeRWtpbac3TaXBxJ1URi6TdhlCvQLeHD8H+kGUJdQpHH+vXAYm8LymEFrbdkniGw7srxqraQsi",
	"HS3z+oO2bmLQQqKVwsTJMx/1anurSgrr+lzRfjNN8s9XmGt7k9JocvBAoU3hAuz06bXHb2wqHXUee95B",
	"bZof+sxqVTZWqZCAhUwIeB1USjoLWwm5yW0QjjVaG/wXFmwi8lYd8nAwGAzim08+k5ZvpOyrybs6fSNF",
	"m+kqUawZX9Zzic1OcTtbTJNoQehzZ+5SLmn1uSord1uqnVNpVypcSCULEvD969TVXdUdQIpjUeWUsWoG",
	"CotmVrNuvdyDosqdnCUFtiopJm6vU8pujIErS1Cvb5DpQZ1D1Kq3IDifgPMMFehCOofXY+Ea3XcqXE+k",
	"WunNsaCoMh+r/S9xV8lt7bk2aWt18+N1nNdkmxe6eP0Oz0PVsjr8bGLQN6kb2Do+evUaSuGy7ataFYW4",
	"eIFq4rJo/9GA8V5/vR9f08e4+S7EghJWNBNWqILrgZtRxMoUf6aN5Vz/wMvfoovZ0EMRD5T3GClIdxZQ",
	"jbVJOKT0KCmg+qBl5/cpWOwMBn82PjYrEmZu+pIx9Ny/tHun9cJ86r+WN9apmM47/e4yYTEbm6HRy6gL",
	"jse+iF2JxqWC/Oo928u7N5xI69Cs3HEkLJ5sGq8CkB4fvjo6efLm+Pjouyf/Onl69OzwzYvX60SnG3TX",
	"c47p0Y047zehX7GRmH5/z/n3tCU2EJ9sC6679O/M1ALF9sFb/C5Lj8yVbFK66SvyAEF23JI6rEhH9bdn",
	"NUffviXEsL/gqQA/nbGYOVdGl0RYqrHuqFTQWHZzY6nYq6a6GuXY89lUjukEzQ68vA8iTe2sxLKVGYsE",
	"h2rLBAPp55Rg1I2s/oSrR7gHpdEOE3KMBdIaXbntHQjRycZ1pyYeKrb6GEZVOkF6Mr6IofFQ9JEcFH8U",
	"KgU7VQnk9EkqyIXjKiJH67RCezBUxOrXjaVRbskcU6wwOEu8uTrlAn4sc9+Re1+IUyQn/35nyHWqdAzA",
	"ZywheZjnUzj84XkUR2dorBfjYGd3Z0B40SUqUcpoP3qwM9h5wMbiMlZjv+6x0pcJMl7JRLhWfp5G+9EL",
	"aV0tGX7TiAIdGhvt//gxkrTRhwpNE7D360juw8VmKcE7Aq1vqTJHu4OBr+uVQz+CEmWZy4TZ6/9ktZoN",
	"q9aOX/VAa6nBdclN/lbroIFE7TPzKSnFocEURlPuTBOhvcH9jRi9ij/f/+ngppDWSjUBbaDur/ggMW+j",
	"rJZ56/zxHYnVVkUhzDQolI2msmi+sNB02bdCM52hPOuac8YgJqTvyNte9O7St+WW0fKEPUktYe+C0LrH",
	"Op3emHyWM/HLtrejDPVyCUk3p6AGQCsBA8GjemgM7gAaIqd4QKDU6bSFkGmJ/drX99lE/3y8EgN/v30G",
	"hGomrHrsPSqJA86ly/xXkgeI3KBIp4AX0jq7mTV5wIMIkyg6azCdKWwlS5MsDmGdFnUZz5xx/6NML/uj",
	"2Ry00zN/jW5hYtrtnsnZz7wzJwJtW5n31YtZxB/1yGvYUc39FeZUi+LTQO7eHSA3HFxpB2NdqXQzVAbJ",
	"+qFx33eIwGkncu/drxo9rwRn5eoUilPp4P/bfL/OEAo9orSFKl5TqVmC1vTge74Hn+tzzm2W+vDE4lBZ",
	"VCG7M2irnLIs6Gjl34P5XjlkaHAHiA2fZQ2VwRSx8JT4jS3J1bn/rsYyDCjqojrTeUp7+WSNjjtU/tGJ",
	"xcSg247hDI0cS/REOKv2CeBYqrSnTc+7f9uE2R344R9PjkDaoZIMmzqXIP1WFtP9GXvSAl4kmVATTMMh",
	"elamjdeikxEb8VBZ7jIafkdpfv0ksGZ8C5Icm88YF3wHH4zBcztBuj2pWStA36BjmR/Nd1hXjbM/N0rf",
	"mTdjWBn8yZc82njEQqUCVlgADwcPbp+TUIFprtcI+2yAk4qyaa0CuAnx3t01/uwoGASIYJJdnmCsDQiY",
	"m+UFL0ZL530YF4XzLmyh4OHHt2MVrYb352AUd4DOrlHxCu3PLdlE2zpMlFapm57fjr4XWoNraXyvY8xM",
	"uQcYPNOnd6iYmyk3j5lrNu3SoEVFPih0ZKC+97NKecWV2e9LPym/JXsJ95eWxFKnMwTEhPs1fGvp89LK",
	"Ey4IXddBVmujvhB2Zfa3Qsm+x8UA5kxJgH/oL4Tdq9eWQpqh4rWuMgrTHTgEg2UuppjGlCqS6cR0+rE2",
	"lCF56lOJeWphb3A/XGSTWjEd4XQhkxisBoOV5VQpxdD9a0JOolVac87vduVMx819uE/FVdxdcPCXA9PG",
	"394V2gN2PNDb+q+rdkqfFwLGsb/KKBYhqJwGAQrP14gbdQ95deSoxzC3Boj2lOf/OfSKTtc5ilNoxj93",
	"1VvyOXQNwhotS1Bs+kOz3KXpSfHIwAnjrktk6pujV/Xoj5rbpWu06MdGF60W/bVj0RWtfr0RlTtp7/ur",
	"wms094NUyR+gdb2xNNZxkR3u7TXTdjoNGMpAP8dWv78/W8+0mi6CNFBfTr2iu9/m6q2RdVfDz+IyFCka",
	"BrJ0tm7TpZ4ySAVaITgjlBUJh1V4neFQLd+W2LJVAXrsG1YWvoLw3beubAwlmmYOu82NlOZ2xUi7LFyx",
	"qNXAHI2mIKC59eiMnEzQHIBQUNUcpESGDlLnD7u7O/zKnMCEQZBFUfmLtr/9+z+QaMMXPlmUYqgM8tBN",
	"TbxUYlD0A21EzO/Ay936mpdddSn8YKgWbplsPfvndsNDPVN8udeVmBDDHvW3NnBp3be543FLMOhuA54G",
	"fH8CkxZvTp9Ei3p39w4CIEufO49Ng37DNjUBF8TMbbTm/HNuY1VLOpgHj0uuKhRr4/ispiMrYd+43/+d",
	"cYhHxO8chjxDl2QcieZC4dR7bwo2K8MgQcz/ge7nOXS1OTvmOtXC7mDgKb5PR/vDqCqH0Xt/B6+JQELZ",
	"czQ2hoeDB/NrU32uhtH7oeLl0kGqka3KzzHmximV5egr+b4Wt05NEa4fJqdIIcJSNBJJxrFqhGNtEIRz",
	"WJR+fsJXVDoHAui+CUe9RUy3/rXQoefwd8Wb7kdft20qnBgJi1DNpLeQx78If2iAe/D08eJfKGrk2Kl1",
	"WBByGJ/mrPY07e1ynVBWiWdRHFUmDzei9vt9fpBp6/YfDR4NIoJxIL1Iwp+I/xG4+yU0qhQ5oEpLLf1l",
	"neDUAluUxC+Cl6oW/2oM3BePoW42cuUcw/dkVPFcfRKIcnmyTPLpvAsXSzeqODGrDS5QCvZ2+e7yvwEA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
