/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + DB connectivity
         * @description Returns 200 with `db:"up"` when Postgres answers, 503 with `db:"down"`
         *     when it does not. The mobile app uses this to confirm the backend is
         *     reachable before attempting a sync.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a credential account and start a session */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token into a new session
         * @description The presented refresh token is revoked and a fresh access+refresh pair
         *     is returned. A replayed, expired, or forged token yields 401; rotation
         *     is atomic, so reuse is detected on the second presentation.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a Google authorization code for a session
         * @description The mobile app runs the authorization-code flow via expo-auth-session and
         *     sends the resulting authorization code + redirect_uri here. The server
         *     redeems the code (it is the confidential client holding the Google
         *     client_secret), verifies the email, and find-or-creates the user. PKCE is
         *     intentionally not used: the code is exchanged server-side with the secret,
         *     so there is no code_verifier to thread.
         */
        post: operations["googleAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the presented refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's accounts (pockets and categories) */
        get: operations["listAccounts"];
        put?: never;
        /** Create a pocket or category (chart-of-accounts entry) */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account debit/credit totals and normal-balance-signed amount */
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List posted entries with their lines */
        get: operations["listEntries"];
        put?: never;
        /**
         * Post a balanced double-entry transaction
         * @description Writes the entry header and its balanced lines in one transaction. The
         *     balance invariant (sum of debits = sum of credits, per currency) is
         *     enforced both in-application and by a Postgres trigger; an unbalanced
         *     entry yields 422. Posted entries are immutable — correct with a
         *     reversing entry, never an edit. M2 supports single-currency entries;
         *     cross-currency (FX) entries land in M4.
         */
        post: operations["postEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one posted entry with its lines */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a month's budgets with live spent totals */
        get: operations["listBudgets"];
        put?: never;
        /** Create or update a monthly category budget */
        post: operations["setBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a budget's target */
        put: operations["updateBudget"];
        post?: never;
        /** Delete a budget (idempotent) */
        delete: operations["deleteBudget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull changes since a watermark (WatermelonDB)
         * @description Returns all records on synced tables (accounts, entries, journal_lines,
         *     budgets) whose server updated_at is after last_pulled_at, split into
         *     created/updated/deleted per table, plus a new timestamp watermark. The
         *     mobile passes the returned timestamp as last_pulled_at on the next pull.
         */
        get: operations["syncPull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push local changes to the server (WatermelonDB)
         * @description Applies client-created/updated/deleted records per table. Entries re-run
         *     the balance invariant; an unbalanced or otherwise invalid pushed entry
         *     is reported in `errors` keyed by client id, never silently dropped.
         *     Accepted records get a server updated_at; LWW on metadata mutables.
         */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fx/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available FX rates
         * @description Returns available base currencies and their latest rate dates.
         *     The mobile calls this to check whether the local rate cache is stale.
         */
        get: operations["listFxRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fx/rates/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a manual FX rate refresh from frankfurter.app
         * @description Fetches today's rates for the configured base currencies. Idempotent.
         *     Returns the number of rates inserted or updated.
         */
        post: operations["refreshFxRates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fx/rates/{base}/{quote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the most recent rate for a currency pair */
        get: operations["getFxRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Net worth (assets minus liabilities) in base currency
         * @description Aggregates all asset and liability accounts, converting each to the
         *     user's base currency using the most recent available FX rate.
         */
        get: operations["getNetWorth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending by category for a period */
        get: operations["getSpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income vs expense for a period, in base currency */
        get: operations["getCashFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's recurring transaction rules */
        get: operations["listRecurring"];
        put?: never;
        /** Create a recurring transaction rule */
        post: operations["createRecurring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one recurring rule */
        get: operations["getRecurring"];
        /** Update a recurring rule */
        put: operations["updateRecurring"];
        post?: never;
        /** Delete a recurring rule (idempotent) */
        delete: operations["deleteRecurring"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually trigger materialization of due recurring rules
         * @description Evaluates the authenticated user's active recurring rules and posts
         *     entries for any that are due (next_run ≤ today), including occurrences
         *     missed while the scheduler was down. Posting is idempotent per
         *     (rule, occurrence date), so repeat calls never double-post. Returns the
         *     count of entries actually created.
         */
        post: operations["triggerRecurring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /**
             * @description process liveness
             * @example ok
             */
            status: string;
            /**
             * @description Postgres connectivity
             * @example up
             * @enum {string}
             */
            db: "up" | "down";
        };
        Error: {
            /**
             * @description stable machine code for this error class
             * @example invalid_credentials
             */
            code: string;
            /**
             * @description human-readable detail
             * @example invalid credentials
             */
            message: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /**
             * @description ISO 4217 currency code
             * @example IDR
             */
            base_currency: string;
            /** Format: date-time */
            created_at: string;
        };
        AuthResponse: {
            /** @description short-lived HS256 JWT; send as `Authorization: Bearer <token>` */
            access_token: string;
            /** @description single-use opaque token; rotate via /auth/refresh */
            refresh_token: string;
            user: components["schemas"]["User"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /**
             * @description optional; defaults to server BASE_CURRENCY_DEFAULT
             * @example IDR
             */
            base_currency?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        GoogleRequest: {
            /** @description authorization code from expo-auth-session */
            code: string;
            /** @description the redirect URI the app used in the auth request */
            redirect_uri: string;
        };
        /**
         * @description Chart-of-accounts type. asset/liability are pockets; income/expense/equity are categories.
         * @enum {string}
         */
        AccountType: "asset" | "liability" | "income" | "expense" | "equity";
        Account: {
            /** @description client-generated id (WatermelonDB) or server uuid */
            id: string;
            type: components["schemas"]["AccountType"];
            /**
             * @description ISO 4217 currency code
             * @example IDR
             */
            currency: string;
            name: string;
            /** @description optional parent account (tree hook; unused in M2) */
            parent_id?: string | null;
            archived: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NewAccountRequest: {
            /** @description optional client id; server generates a uuid when omitted (REST path) */
            id?: string;
            type: components["schemas"]["AccountType"];
            /** @example IDR */
            currency: string;
            name: string;
            parent_id?: string | null;
        };
        JournalLine: {
            /** @description client-generated id */
            id: string;
            entry_id: string;
            account_id: string;
            /** @enum {string} */
            dc: "debit" | "credit";
            /**
             * Format: int64
             * @description unsigned integer minor units (cents) at the currency's scale
             * @example 50000
             */
            amount_minor: number;
            /** @example IDR */
            currency: string;
        };
        LineInput: {
            /** @description optional client id; server generates a uuid when omitted */
            id?: string;
            account_id: string;
            /** @enum {string} */
            dc: "debit" | "credit";
            /**
             * Format: int64
             * @description unsigned minor units
             */
            amount_minor: number;
            /**
             * @description optional; defaults to the entry currency (M4 multi-currency support)
             * @example IDR
             */
            currency?: string;
        };
        Entry: {
            /** @description client-generated id or server uuid */
            id: string;
            /** Format: date */
            txn_date: string;
            /** @enum {string} */
            status: "draft" | "posted";
            /** @example IDR */
            currency: string;
            /** @description cross-currency rate (M4); null for single-currency entries */
            fx_rate?: string | null;
            /** @enum {string} */
            source: "manual" | "recurring" | "import";
            memo: string;
            lines: components["schemas"]["JournalLine"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NewEntryRequest: {
            /** @description optional client id; server generates a uuid when omitted (REST path) */
            id?: string;
            /**
             * Format: date
             * @description optional; defaults to today
             */
            txn_date?: string;
            /** @example IDR */
            currency: string;
            /**
             * @description optional cross-currency rate; when set, the balance invariant is enforced in-app (M4)
             * @example 15000.00
             */
            fx_rate?: string;
            memo?: string;
            /** @enum {string} */
            source?: "manual" | "recurring" | "import";
            lines: components["schemas"]["LineInput"][];
        };
        AccountBalance: {
            account_id: string;
            /** @example IDR */
            currency: string;
            /** Format: int64 */
            debit_minor: number;
            /** Format: int64 */
            credit_minor: number;
            /**
             * Format: int64
             * @description normal-balance-signed amount (asset/expense = debit−credit; others = credit−debit); positive is healthy/normal
             */
            signed_minor: number;
        };
        Budget: {
            id: string;
            /** @description the expense account (category) this budget targets */
            account_id: string;
            /**
             * Format: date
             * @description first day of the month (YYYY-MM-01)
             */
            period_month: string;
            /** Format: int64 */
            target_minor: number;
            /** @example IDR */
            currency: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NewBudgetRequest: {
            /** @description optional client id; server generates a uuid when omitted */
            id?: string;
            account_id: string;
            /**
             * Format: date
             * @description must be the first day of a month
             */
            period_month: string;
            /** Format: int64 */
            target_minor: number;
        };
        BudgetWithSpent: {
            id: string;
            account_id: string;
            /** Format: date */
            period_month: string;
            /** Format: int64 */
            target_minor: number;
            /**
             * Format: int64
             * @description live total of posted debit lines on the account this month
             */
            spent_minor: number;
            /** @example IDR */
            currency: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Per-table change buckets. Keys are table names: accounts, entries,
         *     journal_lines, budgets. Each table maps to created/updated/deleted.
         */
        SyncChanges: {
            [key: string]: components["schemas"]["SyncTableChanges"];
        };
        SyncTableChanges: {
            created?: {
                [key: string]: unknown;
            }[];
            updated?: {
                [key: string]: unknown;
            }[];
            deleted?: string[];
        };
        SyncPullResponse: {
            changes: components["schemas"]["SyncChanges"];
            /**
             * Format: int64
             * @description new watermark; pass as last_pulled_at on the next pull
             */
            timestamp: number;
        };
        SyncPushRequest: {
            changes: components["schemas"]["SyncChanges"];
        };
        FxRate: {
            /** @example USD */
            base: string;
            /** @example IDR */
            quote: string;
            /** Format: date */
            day: string;
            /**
             * @description decimal rate (1 base = rate quote)
             * @example 15000.00
             */
            rate: string;
            /** @example frankfurter */
            source: string;
        };
        FxRateList: {
            rates: components["schemas"]["FxRate"][];
            /** Format: date */
            as_of: string;
        };
        FxRefreshResult: {
            /** @description number of rates inserted or updated */
            count: number;
        };
        NetWorth: {
            base_currency: string;
            /** Format: date-time */
            as_of_date: string;
            total_asset: components["schemas"]["NormalizedAmount"];
            total_liability: components["schemas"]["NormalizedAmount"];
            /** Format: int64 */
            net_minor: number;
        };
        NormalizedAmount: {
            /**
             * Format: int64
             * @description total in the original currencies
             */
            raw_minor: number;
            /** @description the base currency used for normalization */
            currency: string;
            /**
             * Format: int64
             * @description total normalized to base currency
             */
            base_minor: number;
        };
        CategorySpend: {
            account_id: string;
            account_name: string;
            currency: string;
            /** Format: int64 */
            spent_minor: number;
            /** Format: int64 */
            base_minor: number;
        };
        CashFlow: {
            base_currency: string;
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            income_minor: components["schemas"]["NormalizedAmount"];
            expense_minor: components["schemas"]["NormalizedAmount"];
            /** Format: int64 */
            net_minor: number;
        };
        RecurringRule: {
            id: string;
            user_id: string;
            /**
             * @description iCalendar RRULE string (e.g. "FREQ=MONTHLY;BYMONTHDAY=1")
             * @example FREQ=MONTHLY;BYMONTHDAY=1
             */
            rrule: string;
            template: components["schemas"]["RecurringTemplate"];
            /**
             * Format: date
             * @description next scheduled occurrence date
             */
            next_run?: string | null;
            /**
             * Format: date
             * @description most recent materialized occurrence date
             */
            last_run?: string | null;
            active: boolean;
            /** @description why the most recent materialization failed (e.g. the template's account was archived); null once the rule posts successfully again */
            last_error?: string | null;
            /** Format: date-time */
            last_error_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RecurringTemplate: {
            /** @example IDR */
            currency: string;
            memo?: string;
            /** @default recurring */
            source: string;
            lines: components["schemas"]["RecurringLineTemplate"][];
        };
        RecurringLineTemplate: {
            account_id: string;
            /** @enum {string} */
            dc: "debit" | "credit";
            /** Format: int64 */
            amount_minor: number;
            /** @description optional; defaults to the template currency */
            currency?: string;
        };
        NewRecurringRuleRequest: {
            /** @description optional client id; server generates a uuid when omitted */
            id?: string;
            /** @example FREQ=MONTHLY;BYMONTHDAY=1 */
            rrule: string;
            template: components["schemas"]["RecurringTemplate"];
            /** @default true */
            active: boolean;
        };
        UpdateRecurringRuleRequest: {
            rrule: string;
            template: components["schemas"]["RecurringTemplate"];
            active?: boolean;
        };
        RecurringTriggerResult: {
            /** @description number of entries materialized */
            count: number;
        };
        SyncPushResponse: {
            /** @description per-client-id error message for rejected records (never silently dropped) */
            errors?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description malformed body or weak password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description rotated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description token invalid, expired, or already used */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleRequest"];
            };
        };
        responses: {
            /** @description session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description code rejected or email unverified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description google oauth not configured on the server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                type?: components["schemas"]["AccountType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description accounts, optionally filtered by type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccountRequest"];
            };
        };
        responses: {
            /** @description account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description malformed body or invalid type/currency/name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description an account of this type with this name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description account balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalance"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEntries: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description entries newest-first within the optional date range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewEntryRequest"];
            };
        };
        responses: {
            /** @description entry posted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description malformed body or invalid lines */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description entry is not balanced */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listBudgets: {
        parameters: {
            query: {
                /** @description first day of the month (YYYY-MM-01) */
                period: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description budgets with spent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetWithSpent"][];
                };
            };
            /** @description missing or invalid period */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBudgetRequest"];
            };
        };
        responses: {
            /** @description budget created or updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            /** @description malformed body or account is not an owned expense account */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    target_minor: number;
                };
            };
        };
        responses: {
            /** @description budget updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description budget deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    syncPull: {
        parameters: {
            query?: {
                last_pulled_at?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description change set + new watermark */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description apply result with per-record errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listFxRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description available FX rate bases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxRateList"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshFxRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description rates refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxRefreshResult"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFxRate: {
        parameters: {
            query?: {
                /** @description optional as-of date (defaults to today) */
                as_of?: string;
            };
            header?: never;
            path: {
                /** @description ISO 4217 base currency */
                base: string;
                /** @description ISO 4217 quote currency */
                quote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the rate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxRate"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description rate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getNetWorth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description net worth breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorth"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSpending: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description spending per category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySpend"][];
                };
            };
            /** @description invalid date range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCashFlow: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cash flow summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlow"];
                };
            };
            /** @description invalid date range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description recurring rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"][];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRecurringRuleRequest"];
            };
        };
        responses: {
            /** @description rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
            /** @description invalid rrule or template */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the recurring rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringRuleRequest"];
            };
        };
        responses: {
            /** @description rule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
            /** @description invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description rule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    triggerRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description materialization complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTriggerResult"];
                };
            };
            /** @description missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
